// <auto-generated />
using System;
using LojaProdutosCurso.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LojaProdutosCurso.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251215130443_adicionandoUsuario")]
    partial class adicionandoUsuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LojaProdutosCurso.Models.CategoriaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Eletrônicos"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Roupas"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Calçados"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Livros"
                        });
                });

            modelBuilder.Entity("LojaProdutosCurso.Models.EnderecoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Complemento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioModelId")
                        .IsUnique();

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("LojaProdutosCurso.Models.ProdutoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaModelId")
                        .HasColumnType("int");

                    b.Property<string>("Foto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuantidadeEstoque")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaModelId");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaModelId = 1,
                            Foto = "smartphone_xyz.jpg",
                            Marca = "MarcaA",
                            Nome = "Smartphone XYZ",
                            QuantidadeEstoque = 50,
                            Valor = 1500.00m
                        },
                        new
                        {
                            Id = 2,
                            CategoriaModelId = 1,
                            Foto = "notebook_abc.jpg",
                            Marca = "MarcaB",
                            Nome = "Notebook ABC",
                            QuantidadeEstoque = 30,
                            Valor = 3500.00m
                        },
                        new
                        {
                            Id = 3,
                            CategoriaModelId = 2,
                            Foto = "camiseta_casual.jpg",
                            Marca = "MarcaC",
                            Nome = "Camiseta Casual",
                            QuantidadeEstoque = 100,
                            Valor = 80.00m
                        },
                        new
                        {
                            Id = 4,
                            CategoriaModelId = 3,
                            Foto = "tenis_esportivo.jpg",
                            Marca = "MarcaD",
                            Nome = "Tênis Esportivo",
                            QuantidadeEstoque = 75,
                            Valor = 200.00m
                        },
                        new
                        {
                            Id = 5,
                            CategoriaModelId = 4,
                            Foto = "livro_csharp_avancado.jpg",
                            Marca = "EditoraX",
                            Nome = "Livro de C# Avançado",
                            QuantidadeEstoque = 40,
                            Valor = 120.00m
                        });
                });

            modelBuilder.Entity("LojaProdutosCurso.Models.ProdutosBaixadosModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataDaBaixa")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProdutoModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoModelId");

                    b.ToTable("ProdutosBaixados");
                });

            modelBuilder.Entity("LojaProdutosCurso.Models.UsuarioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cargo")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("SenhaSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("LojaProdutosCurso.Models.EnderecoModel", b =>
                {
                    b.HasOne("LojaProdutosCurso.Models.UsuarioModel", "Usuario")
                        .WithOne("Endereco")
                        .HasForeignKey("LojaProdutosCurso.Models.EnderecoModel", "UsuarioModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LojaProdutosCurso.Models.ProdutoModel", b =>
                {
                    b.HasOne("LojaProdutosCurso.Models.CategoriaModel", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("LojaProdutosCurso.Models.ProdutosBaixadosModel", b =>
                {
                    b.HasOne("LojaProdutosCurso.Models.ProdutoModel", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("LojaProdutosCurso.Models.UsuarioModel", b =>
                {
                    b.Navigation("Endereco")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
